stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='product'),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/stepshop/views.py
from django.shortcuts import render


links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def index(request):
    title = "главная"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'index.html', context)


def contacts(request):
    title = "контакты"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'contacts.html', context)


def about(request):
    title = "о нас"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'about.html', context)

stepshop/stepshop/templates/includes/inc_category_menu.html
<div class="featured-page">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h1>{{ title|capfirst }}</h1>
                </div>
            </div>
            <div class="col-md-8 col-sm-12">
                <div id="filters" class="button-group">

                    <button class="btn btn-primary" data-filter="*">
                        <a class="{% if request.resolver_match.kwargs.pk == 0 %}
                                    active
                                  {% elif request.resolver_match.kwargs.pk == None %}
                                    active
                                  {% endif %}
                                 " href="{% url 'products:category' 0 %}">
                            Все
                        </a>
                    </button>

                    {% for category in categories %}
                        <button class="btn btn-primary"
                                data-filter="{{ category.name }}">
                            <a href="{% url 'products:category' category.pk %}"
                               class="{% if request.resolver_match.kwargs.pk == category.pk %}
                                         active
                                      {% endif %}
                            ">
                                {{ category.name|capfirst }}
                            </a>
                        </button>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

stepshop/stepshop/templates/includes/inc_main_menu.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#"><img src="{% static 'assets/images/header-logo.png' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        {% for item in links_menu %}
        <li class="nav-item
          {% if request.resolver_match.route == item.route %}
            active
          {% endif %}
        ">
          <a class="nav-link" href="{% url item.href %}">{{ item.name }}</a>
            {% if request.resolver_match.route == item.route %}
              <span class="sr-only">(current)</span>
            {% endif %}
        </li>
        {% endfor %}

      </ul>
    </div>
  </div>
</nav>