stepshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp
from adminapp.views import UsersListView, UserCreateView


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

stepshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='product'),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/stepshop/views.py
from django.shortcuts import render


links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def index(request):
    title = "главная"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'index.html', context)


def contacts(request):
    title = "контакты"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'contacts.html', context)


def about(request):
    title = "о нас"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'about.html', context)

stepshop/stepshop/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title|title }}{% endblock %}

{% block content %}

    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="about-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>О нас</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-image">
              <img src="{% static 'assets/images/about-us.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>Phasellus vel interdum elit</h4>
              <p><a href="https://www.pexels.com/photo/group-of-people-raising-right-hand-1059120/">Photo Credit</a> goes to Pexels website. Aliquam erat volutpat. Pellentesque fringilla, ligula consectetur cursus scelerisque, leo elit pellentesque sapien, et pharetra arcu elit vitae sem. Suspendisse erat dui, condimentum in mi ac, varius tempor sapien. Donec in justo sit amet ex aliquet maximus ac quis erat.</p> 
              <br>
              <p>Donec fermentum tincidunt tellus quis fermentum. Proin eget imperdiet purus. Nulla facilisi. Aliquam tincidunt porttitor dui sed euismod. Duis est libero, rhoncus fermentum turpis id, tempus fringilla ipsum. Nullam venenatis tincidunt neque vel hendrerit. Suspendisse porta pretium porttitor.</p>
              <br>
              <p>Sed purus quam, ultricies eu leo in, sollicitudin varius quam. Proin dictum urna ac diam fermentum tempus. Pellentesque urna urna, ullamcorper a tincidunt dignissim, venenatis in nisi. Vivamus in volutpat tellus. Etiam fermentum luctus posuere.</p>
              <br>
              <p><a rel="nofollow" href="https://www.tooplate.com/view/2114-pixie">Pixie HTML Template</a> can be converted into your desired CMS theme. You can use this Bootstrap v4.1.3 layout for any online shop. Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a>. Thank you.</p>
              <div class="share">
                <h6>Find us on: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->

{% endblock %}

stepshop/stepshop/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ru">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>{% block title %}Pixie - Ecommerce HTML5 Template{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    {% block css %}
    {% endblock %}
<!--
Tooplate 2114 Pixie
https://www.tooplate.com/view/2114-pixie
-->
  </head>

  <body>

    <!-- Pre Header -->
    <div id="pre-header">
      <div class="container">
        <div class="row">
          <div class="col-md-12 d-flex justify-content-end align-items-center text-light">

            {% if user.is_authenticated %}
              {% if user.is_superuser %}
                <a href="{% url 'admin_staff:users' %}" class="nav-link">
                  <span>Админка</span>
                </a>
              |
              {% endif %}
                <a href="{% url 'auth:edit' %}" class="nav-link">
                  <span>{{ user.first_name|default:'Пользователь' }}</span>
                </a>
              |
                <a href="{% url 'auth:logout' %}" class="nav-link">
                  <span>Выйти</span>
                </a>
              {% else %}
                <a href="{% url 'auth:login' %}" class="nav-link">
                  <span>Войти</span>
                </a>
              {% endif %}

            {% if basket %}
              <a href="{% url 'basket:view' %}" class="basket mr-2">
                <span>{{ basket.0.total_quantity }}</span>
              </a>
            <span>${{ basket.0.total_cost|floatformat:"g" }}</span>
            {% endif %}

          </div>
        </div>
      </div>
    </div>

    {% include 'includes/inc_main_menu.html' %}

    {% block content %}
      Сюда подставляется контент
    {% endblock %}

    <!-- Sub Footer Starts Here -->
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright-text">
              <p>Copyright &copy; 2019&ndash;{% now "Y" %} Бобёр Inc.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Sub Footer Ends Here -->


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>


    <script language = "text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

    {% block js %}
    {% endblock %}

  </body>

</html>

stepshop/stepshop/templates/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Контакты &ndash; нормальное название{% endblock %}

{% block content %}

    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="contact-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Contact Us</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div id="map">
            		<!-- How to change your own map point
                           1. Go to Google Maps
                           2. Click on your location point
                           3. Click "Share" and choose "Embed map" tab
                           4. Copy only URL and paste it within the src="" field below
                    -->

              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1197183.8373802372!2d-1.9415093691103689!3d6.781986417238027!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdb96f349e85efd%3A0xb8d1e0b88af1f0f5!2sKumasi+Central+Market!5e0!3m2!1sen!2sth!4v1532967884907" width="100%" height="500px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="container">
                <form id="contact" action="" method="post">
                  <div class="row">
                    <div class="col-md-6">
                      <fieldset>
                        <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-6">
                      <fieldset>
                        <input name="email" type="text" class="form-control" id="email" placeholder="Your email..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="button">Send Message</button>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <div class="share">
                        <h6>You can also keep in touch on: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->

{% endblock %}

stepshop/stepshop/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title|title }}{% endblock %}

{% block content %}

<!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="banner">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="caption">
              <h2>Ecommerce HTML Template</h2>
              <div class="line-dec"></div>
              <p>Pixie HTML Template can be converted into your desired CMS theme. Total <strong>5 pages</strong> included. You can use this Bootstrap v4.1.3 layout for any CMS.
              <br><br>Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a> free template site. Thank you. Photo credit goes to <a rel="nofollow" href="https://www.pexels.com">Pexels website</a>.</p>
              <div class="main-button">
                <a href="#">Order Now!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <!-- Featured Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Featured Items</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-01.jpg' %}" alt="Item 1">
                  <h4>Proin vel ligula</h4>
                  <h6>$15.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-02.jpg' %}" alt="Item 2">
                  <h4>Erat odio rhoncus</h4>
                  <h6>$25.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-03.jpg' %}" alt="Item 3">
                  <h4>Integer vel turpis</h4>
                  <h6>$35.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-04.jpg' %}" alt="Item 4">
                  <h4>Sed purus quam</h4>
                  <h6>$45.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-05.jpg' %}" alt="Item 5">
                  <h4>Morbi aliquet</h4>
                  <h6>$55.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-06.jpg' %}" alt="Item 6">
                  <h4>Urna ac diam</h4>
                  <h6>$65.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-04.jpg' %}" alt="Item 7">
                  <h4>Proin eget imperdiet</h4>
                  <h6>$75.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-05.jpg' %}" alt="Item 8">
                  <h4>Nullam risus nisl</h4>
                  <h6>$85.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="{% static 'assets/images/item-06.jpg' %}" alt="Item 9">
                  <h4>Cras tempus</h4>
                  <h6>$95.00</h6>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Featred Ends Here -->

{% endblock %}

stepshop/stepshop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}{{ title|capfirst }}: {{ product.name }}{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>{{ product.name }}</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="product-slider">
              <div id="slider" class="flexslider">
                 <img src="{{ product.image|media_folder_products }}"
                      alt="{{ product.name }}"
                      title="{{ product.name }}"
                      class="img-fluid">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>{{ product.name }}</h4>
              <h6>${{ product.price|floatformat:"2g" }}</h6>
              <p>{{ product.description }}</p>
              <div>Количество на складе: <span>{{ product.quantity }}</span></div>

              <div class="btn main-button p-0">
                <a href="{% url 'basket:add' product.pk %}">Заказать</a>
              </div>

              <div class="down-content">
                <div class="categories">
                  <h6>Категория: <span><a href="">{{ category|capfirst }}</a></span></h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Похожие продукты</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">

              {% for product in same_products %}
              <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                   <img src="{{ product.image|media_folder_products }}"
                        alt="{{ product.name }}"
                        title="{{ product.name }}">
                  <h4>{{ product.name }}</h4>
                  <h6>${{ product.price }}</h6>
                </div>
              </a>
              {% endfor %}
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-02.jpg" alt="Item 2">-->
<!--                  <h4>Erat odio rhoncus</h4>-->
<!--                  <h6>$25.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-03.jpg" alt="Item 3">-->
<!--                  <h4>Integer vel turpis</h4>-->
<!--                  <h6>$35.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-04.jpg" alt="Item 4">-->
<!--                  <h4>Sed purus quam</h4>-->
<!--                  <h6>$45.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-05.jpg" alt="Item 5">-->
<!--                  <h4>Morbi aliquet</h4>-->
<!--                  <h6>$55.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-06.jpg" alt="Item 6">-->
<!--                  <h4>Urna ac diam</h4>-->
<!--                  <h6>$65.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-04.jpg" alt="Item 7">-->
<!--                  <h4>Proin eget imperdiet</h4>-->
<!--                  <h6>$75.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-05.jpg" alt="Item 8">-->
<!--                  <h4>Nullam risus nisl</h4>-->
<!--                  <h6>$85.00</h6>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="single-product.html">-->
<!--                <div class="featured-item">-->
<!--                  <img src="assets/images/item-06.jpg" alt="Item 9">-->
<!--                  <h4>Cras tempus</h4>-->
<!--                  <h6>$95.00</h6>-->
<!--                </div>-->
<!--              </a>-->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Similar Ends Here -->

{% endblock %}

stepshop/stepshop/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}{{ title|capfirst }}{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- Items Starts Here -->
    {% include 'includes/inc_category_menu.html' %}
  
    <div class="featured container no-gutter">
        <div class="row posts">

          {% for product in products %}
          <div id="{{ product.id }}" class="item new col-md-4">
              <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                  <img src="{{ product.image|media_folder_products }}"
                       alt="{{ product.name }}">
                  <h4>{{ product.name }}</h4>
                  <h6>${{ product.price }}</h6>
                </div>
              </a>
          </div>
          {% endfor %}

        </div>
    </div>

    <div class="page-navigation">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul>
              <li class="current-page"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- Featred Page Ends Here -->

{% endblock %}