stepshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp
from adminapp.views import UsersListView, UserCreateView


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/stepshop/views.py
from django.shortcuts import render


links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def index(request):
    title = "главная"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'index.html', context)


def contacts(request):
    title = "контакты"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'contacts.html', context)


def about(request):
    title = "о нас"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'about.html', context)

stepshop/stepshop/templates/admin_staff/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/admin_staff.css' %}">
        <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/fontawesome.css' %}">

    {% block css %}
    {% endblock %}

    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script src="{% static 'assets/js/admin_staff.js' %}"></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'admin_staff/includes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:login' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

stepshop/stepshop/templates/admin_staff/categories.html
{% extends 'admin_staff/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории продуктов
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in categories_list %}
                            <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{#% url 'admin_staff:products' category.id %#}"
                                       style="color: dodgerblue">{{ category.name }}</a></td>
                                <td class="text-center">
                                    <a {% if not category.is_active %} class="invisible" {% endif %}
                                       href="{#% url 'admin_staff:category_update' pk=category.id %#}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <a {% if not category.is_active %} class="invisible" {% endif %}
                                       href="{#% url 'admin_staff:category_delete' pk=category.id %#}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{#% url 'admin_staff:category_create' %#}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

stepshop/stepshop/templates/admin_staff/products.html
{% extends 'admin_staff/base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <h1 class="mt-4">Продукты
            {% if category %}
                :<span>{{ category.name }}</span>
            {% endif %}
        </h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                <a href="{% url 'admin_staff:categories' %}">Категории</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Изображение</th>
                            <th>Имя</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Изображение</th>
                            <th>Имя</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                            {% for object in products_list %}
                                <tr>
                                <td><img src="/media/{{object.image|default:'products_images/default.jpg'}}"
                                  alt="{{ object.name }}" style="width:50px;">
                                </td>
                                <td>
                                  {{ object.name|title }}
                                </td>
                                <td>
                                  {{ object.short_desc|title }}
                                </td>
                                <td>{{ object.quantity }}</td>
                                <td>{{ object.price }} руб</td>
                                <td>
                                  <button type="button" class="btn btn-primary">
                                    <a class="text-white" href="{% url 'admin_staff:product_read' object.pk %}">
                                      подробнее
                                    </a>
                                  </button>
                                </td>
                                <td>
                                  <button class="btn btn-warning">
                                    <a class="text-dark" href="{% url 'admin_staff:product_update' object.pk %}">
                                      редактировать
                                    </a>
                                  </button>
                                    </td>
                                <td>
                                  <button class="btn btn-danger">
                                    <a class="text-white" href="{% url 'admin_staff:product_delete' object.pk %}">
                                      удалить
                                    </a>
                                  </button>
                                </td>
                                </tr>
                            {% endfor%}
                        </tbody>
                    </table>

            <div class="card-footer">
                <button class="btn btn-success">
                  <a class="text-white" href="{% url 'admin_staff:product_create' category.pk %}">
                    новый продукт
                  </a>
                </button>
            </div>

  </div>

{% endblock %}

stepshop/stepshop/templates/admin_staff/user_create.html
{% extends 'admin_staff/base.html' %}
{% load static %}

{% block content %}
    <div class="mx-auto col-3">
        <form action="{% url 'admin_staff:user_create' %}"
              method="post"
              enctype="multipart/form-data"
              class="form-horizontal">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" class="form-control" value="Создать">
        </form>
    </div>
{% endblock %}

stepshop/stepshop/templates/admin_staff/users.html
{% extends 'admin_staff/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in users_list %}
                            <tr {% if not user.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{#% url 'admin_staff:user_update' user.id %#}"
                                       style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td class="text-center">
                                    <a {% if not user.is_active %} class="invisible" {% endif %} href="{#% url 'admin_staff:user_delete' pk=user.id %#}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    {% if page_obj.paginator %}
                    {% if page_obj.paginator.num_pages > 1 %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; первая</a>
                                <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                            {% endif %}
                        </span>
                        <span class="current">
                            {% if page_obj.has_previous %}
                                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                            {% endif %}
                        </span>
                        <span class="step-links">
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                    {% endif %}
                    {% endif %}

                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}