stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/stepshop/views.py
from django.shortcuts import render


links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def index(request):
    title = "главная"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'index.html', context)


def contacts(request):
    title = "контакты"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'contacts.html', context)


def about(request):
    title = "о нас"

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'about.html', context)

stepshop/stepshop/templates/basket/includes/inc_basket_list.html
<table class="table mt-3">
    <thead>
    <tr>
        <th class="col-1">№</th>
        <th class="col">Продукт</th>
        <th class="col">Количество</th>
        <th class="col">Стоимость</th>
        <th class="col">Удалить</th>
    </tr>
    </thead>
    <tbody>
    {% for item in basket %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>
            <input type="number"
                   name="{{ item.pk }}"
                   min="0"
                   value="{{ item.quantity }}">
        </td>
        <td>{{ item.product_cost }}</td>
        <td>
            <button class="btn btn-round">
                <a href="{% url 'basket:remove' item.pk %}">удалить</a>
            </button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% if basket %}
<div class="basket_summary">
    Всего товаров: <strong>{{ basket.0.total_quantity }}</strong><br>
    Общая стоимость: <strong>${{ basket.0.total_cost|floatformat:"g" }}</strong>
</div>
{% endif %}